### ISSUE TITLE
NO_IFADDRS code doesn't work

### ISSUE THREAD

**Issue by wrathematics** [wrathematics/getip#3]
Ping @snoweye 

Getting the package ready for CRAN, I've found some issues with the `NO_IFADDRS` case. There were 2 versions in the git history. The first has no errors, but doesn't seem to work on non-Linux platforms. The second has memory errors that lead to unpredictable segfaults. I ran the second through valgrind, but couldn't see how to resolve the problem without basically reverting to something like the first. But the first doesn't work; it always throws `ERRMSG`.

Since this is just for solaris (or aix or other platforms nobody actually uses), I don't see what else to do but to make those platforms throw the "unsupported" error https://github.com/wrathematics/getip/blob/master/src/ip_internal.c#L240-L244. It will still build on solaris for CRAN, but using the function will just produce an R stop error.

If it's obvious to you what's wrong and you can point me in the right direction, I'll take another look. But I don't really see how else to handle this right now.

**Comment by snoweye** [comment]
I can not recall this. I will try to see if I can find time over this weekend. Perhaps, I ran in the same problems and I can not fix at that time, so I sneaked around it, but somehow slipped in a puddle ...

I lost in the triple negative sentence ... what do you mean "... no errors, but doesn't ... non-Linux ..."

**Comment by wrathematics** [comment]
Yeah sorry, I was in a hurry when I wrote that.

* "Version 1"  is the currently live, and first implementation; the one with the hard-coded limit
* "Version 2" is the version from [this commit](https://github.com/wrathematics/getip/blob/004667c6bba085abfe33a21c6ea38e8094b5b18c/src/ip_internal.c)
* Both compile without any warnings. But version 2 has memory errors, sometimes leading to segfaults.
* Version 1 has no run-time errors and produces the correct result on Linux. On my Mac, it doesn't find anything and gets to the `error(ERRMSG)` part of the logic. I think version 2 does the same, but now I don't remember.

I think one problem with version 1 is that `MAX_IFR` definitely needs to be a lot bigger; maybe 64 or 128.  Just on my Mac with 2 devices, `ifc_num` was something like 15. It's possible I don't understand what this is doing though. Anyway, that change alone didn't fix it.

**Comment by snoweye** [comment]
- `MAX_IFR` is in version 2?
- Would the array `struct ifreq ifr[MAX_IFR]` changed to pointer `struct ifreq *ifr, *socket_p;` solve the segfaults? The commit you pointed to use the pointer version and has no `MAX_IFR` any more.
- I am fine without `Solaris` and `Mac`.

**Comment by snoweye** [comment]
- I have tested the MAX_IFR version. No segfaults on xubuntu 16.04, Solaris 10, nor Mac 10.7. Not sure what happen how you get segfaults ...
- Do you use IPv6?

**Comment by wrathematics** [comment]
The `MAX_IFR` version does not segfault. It's the other one ([this one](https://github.com/wrathematics/getip/commit/004667c6bba085abfe33a21c6ea38e8094b5b18c)) that does. However, the `MAX_IFR` version does not work properly. It always reaches the `error(ERRMSG)` logic. 

It correctly looks up my IPv4 address in the `HAS_IFADDRS` version, but does not in either of the `NO_IFADDRS` versions.

**Comment by snoweye** [comment]
- Let's start from here say that is version 3 for [this one](https://github.com/wrathematics/getip/commit/004667c6bba085abfe33a21c6ea38e8094b5b18c). I get confused with your version 2 in the code.
- ... because the MAX_IFR is not larger enough to reach the local ip ... that is why dynamic allocation is needed in that version ... I need to check again.

**Comment by wrathematics** [comment]
I set it to 64 and it was exiting after ~15 iterations, but still producing the `error(ERRMSG)` code.

**Comment by snoweye** [comment]
- The length of `ifr.ifr_addr` may not be the same for different interface and OS.
- The solution may not be potable, but I .tested on Solaris 10, Mac OS 10.7, and Ubuntu 16.04.

**Comment by wrathematics** [comment]
PR seems to work. Thanks!
